//! Parity against LightGBM. The `tiny_*` binary/regression fixtures and their expected values
//! come from bosk (generated with LightGBM 4.6); the multiclass and ranking fixtures are
//! generated by `tests/fixtures/lgbm/make_fixtures.py` with the LightGBM wapul-ml trains with.

use super::*;

macro_rules! fixture {
    ($name:literal) => {
        include_str!(concat!("../../tests/fixtures/lgbm/", $name))
    };
}

fn assert_close(got: &[f64], expected: &[f64], what: &str) {
    assert_eq!(got.len(), expected.len(), "{what}: output count");
    for (k, (g, e)) in got.iter().zip(expected).enumerate() {
        assert!(
            (g - e).abs() < 1e-9,
            "{what}[{k}]: rust={g}, lightgbm={e}, diff={:.2e}",
            (g - e).abs()
        );
    }
}

/// `(row, raw scores, predictions)` per line of a `.cases` file written by `make_fixtures.py`.
fn parse_cases(text: &str) -> Vec<(SparseRow, Vec<f64>, Vec<f64>)> {
    let floats = |s: &str| {
        s.split_whitespace()
            .map(|t| t.parse::<f64>().unwrap())
            .collect::<Vec<_>>()
    };
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let mut parts = line.split('|');
            let row = parts
                .next()
                .unwrap()
                .split_whitespace()
                .map(|p| {
                    let (i, v) = p.split_once(':').unwrap();
                    (i.parse().unwrap(), v.parse().unwrap())
                })
                .collect();
            (
                SparseRow::new(row),
                floats(parts.next().unwrap()),
                floats(parts.next().unwrap()),
            )
        })
        .collect()
}

/// Minimal single-stump model text for exercising header handling.
fn stump(header: &str, leaf: f64) -> String {
    format!("{header}\nTree=0\nnum_leaves=1\nleaf_value={leaf}\n")
}

fn predict1(model: &LgbModel, features: &[f64]) -> f64 {
    let out = model.predict(features).unwrap();
    assert_eq!(out.len(), 1);
    out[0]
}

#[test]
fn objective_transforms() {
    let cases = [
        ("objective=regression", 0.5f64),
        ("objective=regression sqrt", 0.25f64),
        ("objective=binary sigmoid:1", 1.0 / (1.0 + (-0.5f64).exp())),
        ("objective=binary sigmoid:2", 1.0 / (1.0 + (-1.0f64).exp())),
        ("objective=cross_entropy", 1.0 / (1.0 + (-0.5f64).exp())),
        ("objective=cross_entropy_lambda", 0.5f64.exp().ln_1p()),
        ("objective=poisson", 0.5f64.exp()),
        ("objective=tweedie", 0.5f64.exp()),
        ("objective=lambdarank", 0.5f64),
    ];
    for (header, expected) in cases {
        let model = LgbModel::parse(&stump(header, 0.5)).unwrap();
        let got = predict1(&model, &[]);
        assert!(
            (got - expected).abs() < 1e-15,
            "{header}: got {got}, expected {expected}"
        );
    }
    // The sqrt transform must keep the raw score's sign.
    let model = LgbModel::parse(&stump("objective=regression sqrt", -0.5)).unwrap();
    assert_eq!(predict1(&model, &[]), -0.25);
}

#[test]
fn sqrt_objective_selection() {
    for name in ["regression", "regression_l1", "fair", "quantile", "mape"] {
        let sqrt = LgbModel::parse(&stump(&format!("objective={name} sqrt"), 0.5)).unwrap();
        assert_eq!(sqrt.objective, Objective::Sqrt, "{name} sqrt");
        let plain = LgbModel::parse(&stump(&format!("objective={name}"), 0.5)).unwrap();
        assert_eq!(plain.objective, Objective::Identity, "{name}");
    }
}

#[test]
fn average_output() {
    let text = "objective=regression\naverage_output\n\
                Tree=0\nnum_leaves=1\nleaf_value=0.4\n\
                Tree=1\nnum_leaves=1\nleaf_value=0.8\n";
    let model = LgbModel::parse(text).unwrap();
    assert!((predict1(&model, &[]) - 0.6).abs() < 1e-15);
}

#[test]
fn unsupported_models_are_rejected() {
    let three = "Tree=1\nnum_leaves=1\nleaf_value=0.5\nTree=2\nnum_leaves=1\nleaf_value=0.5\n";
    for (name, text) in [
        (
            "one-vs-all",
            stump(
                "objective=multiclassova num_class:3 sigmoid:1\nnum_class=3\nnum_tree_per_iteration=3",
                0.5,
            ) + three,
        ),
        // The objective, num_class and num_tree_per_iteration must agree.
        (
            "class count mismatch",
            stump("objective=multiclass num_class:3\nnum_class=3", 0.5),
        ),
        ("unknown objective", stump("objective=who_knows", 0.5)),
        (
            "unknown binary token",
            stump("objective=binary who_knows", 0.5),
        ),
        (
            "unknown regression token",
            stump("objective=regression who_knows", 0.5),
        ),
        (
            "sqrt on non-sqrt objective",
            stump("objective=huber sqrt", 0.5),
        ),
        (
            "linear tree",
            "objective=regression\nTree=0\nnum_leaves=1\nleaf_value=0.5\nis_linear=1\n".to_string(),
        ),
    ] {
        let err = LgbModel::parse(&text).unwrap_err();
        assert!(
            matches!(err, Error::Unsupported { .. }),
            "{name}: expected Unsupported, got {err:?}"
        );
    }
}

#[test]
fn multiclass_tree_count_must_divide() {
    let header = "objective=multiclass num_class:2\nnum_class=2\nnum_tree_per_iteration=2";
    let err = LgbModel::parse(&stump(header, 0.5)).unwrap_err();
    assert!(matches!(err, Error::Parse { .. }), "got {err:?}");
}

#[test]
fn invalid_sigmoid_parameter_is_rejected() {
    for bad in ["nan", "inf", "0", "-1"] {
        let err =
            LgbModel::parse(&stump(&format!("objective=binary sigmoid:{bad}"), 0.5)).unwrap_err();
        assert!(
            matches!(err, Error::Parse { .. }),
            "sigmoid:{bad}: got {err:?}"
        );
    }
}

/// A tiny binary model (8 trees, 5 features) trained with `boost_from_average=false`.
#[test]
fn lightgbm_parity() {
    let model = LgbModel::parse(fixture!("tiny_binary.lgb")).unwrap();
    assert_eq!(model.num_trees(), 8);
    assert_eq!(model.num_features(), 5);
    assert_eq!(model.objective, Objective::Sigmoid(1.0));
    let pred = predict1(&model, &[0.5, -0.2, 0.7, 1.1, -0.9]);
    assert_close(&[pred], &[0.879687246542221], "tiny_binary");
}

/// Missing values: `tiny_nan.lgb` was trained with NaNs, so its splits carry non-default
/// missing directions.
#[test]
fn lightgbm_nan_parity() {
    let model = LgbModel::parse(fixture!("tiny_nan.lgb")).unwrap();
    let pred = predict1(&model, &[f64::NAN, 0.3, f64::NAN, -0.5, 1.2]);
    assert_close(&[pred], &[0.18514897124790036], "tiny_nan");
}

/// Zero-as-missing: `|v| <= kZeroThreshold` (1e-35) counts as zero, so `1e-40` must predict
/// identically to an exact `0.0` while `1e-30` must not.
#[test]
fn lightgbm_zero_as_missing_parity() {
    let model = LgbModel::parse(fixture!("tiny_zero.lgb")).unwrap();
    let n_zero_splits = model
        .trees
        .iter()
        .flat_map(|t| &t.decision_type)
        .filter(|&&dt| (dt >> 2) & 3 == 1)
        .count();
    assert!(
        n_zero_splits > 0,
        "fixture must contain missing_type=Zero splits"
    );
    let cases: [([f64; 5], f64); 5] = [
        ([0.0, 0.3, 0.0, -0.5, 1.2], 0.30046007383088824),
        ([1e-40, 0.3, 1e-40, -0.5, 1.2], 0.30046007383088824),
        ([1e-30, 0.3, 1e-30, -0.5, 1.2], 0.3412099306576426),
        ([0.5, -0.2, 0.7, 1.1, -0.9], 0.9178425581052003),
        ([0.0, 0.0, 0.0, 0.0, 0.0], 0.5302747959214583),
    ];
    for (features, expected) in cases {
        assert_close(&[predict1(&model, &features)], &[expected], "tiny_zero");
    }
}

/// `reg_sqrt`: the prediction is `sign(raw) * raw^2`; the second case has a negative raw score.
#[test]
fn lightgbm_sqrt_parity() {
    let model = LgbModel::parse(fixture!("tiny_sqrt.lgb")).unwrap();
    assert_eq!(model.objective, Objective::Sqrt);
    let cases: [([f64; 5], f64); 3] = [
        ([0.5, -0.2, 0.7, 1.1, -0.9], 0.6882935825372578),
        ([-1.0, 0.3, -0.4, 0.2, 0.6], -1.305067557709267),
        ([0.0, 0.0, 0.0, 0.0, 0.0], -0.04682388288592408),
    ];
    for (features, expected) in cases {
        assert_close(&[predict1(&model, &features)], &[expected], "tiny_sqrt");
    }
}

/// Categorical splits: in-bitset, unseen (beyond the bitset), negative and NaN categories.
#[test]
fn lightgbm_categorical_parity() {
    let model = LgbModel::parse(fixture!("tiny_cat.lgb")).unwrap();
    let n_cat_splits = model
        .trees
        .iter()
        .flat_map(|t| &t.decision_type)
        .filter(|&&dt| dt & 1 != 0)
        .count();
    assert!(n_cat_splits > 0, "fixture must contain categorical splits");
    let cases: [([f64; 5], f64); 6] = [
        ([0.5, -0.2, 0.7, 1.0, 3.0], 0.973622176489283),
        ([0.5, -0.2, 0.7, 15.0, 0.0], 0.9740570762683468),
        ([-1.0, 0.3, -0.4, 29.0, 11.0], 0.02734900954762666),
        ([-1.0, 0.3, -0.4, 40.0, 25.0], 0.027716944663299832),
        ([0.0, 0.0, 0.0, -1.0, -2.0], 0.038079953138787107),
        ([0.0, 0.0, 0.0, f64::NAN, f64::NAN], 0.038079953138787107),
    ];
    for (features, expected) in cases {
        assert_close(&[predict1(&model, &features)], &[expected], "tiny_cat");
    }
}

/// Multiclass (4 classes, softmax) on sparse input, including an all-absent row.
#[test]
fn lightgbm_multiclass_sparse_parity() {
    let model = LgbModel::parse(fixture!("tiny_multiclass.lgb")).unwrap();
    assert_eq!(model.num_outputs(), 4);
    for (k, (row, raw, pred)) in parse_cases(fixture!("tiny_multiclass.cases"))
        .iter()
        .enumerate()
    {
        assert_close(
            &model.predict_raw_sparse(row),
            raw,
            &format!("multiclass raw, case {k}"),
        );
        assert_close(
            &model.predict_sparse(row),
            pred,
            &format!("multiclass prediction, case {k}"),
        );
    }
}

/// LambdaRank raw scores; sparse and dense input must agree.
#[test]
fn lightgbm_lambdarank_parity() {
    let model = LgbModel::parse(fixture!("tiny_rank.lgb")).unwrap();
    for (k, (row, raw, pred)) in parse_cases(fixture!("tiny_rank.cases")).iter().enumerate() {
        assert_close(&model.predict_sparse(row), pred, &format!("rank, case {k}"));
        let dense: Vec<f64> = (0..model.num_features()).map(|i| row.get(i)).collect();
        assert_close(
            &model.predict_raw(&dense).unwrap(),
            raw,
            &format!("rank dense, case {k}"),
        );
    }
}

#[test]
fn sparse_row_keeps_the_last_of_repeated_indices() {
    let row = SparseRow::new(vec![(5, 1.0), (2, 3.0), (5, 7.0)]);
    assert_eq!(
        (row.get(2), row.get(5), row.get(3), row.get(usize::MAX)),
        (3.0, 7.0, 0.0, 0.0)
    );
}

/// A model body whose single internal node is `split_feature=0`, `threshold=0.5` and the given
/// children.
fn one_split(left: i32, right: i32) -> String {
    format!(
        "Tree=0\nnum_leaves=2\nsplit_feature=0\nthreshold=0.5\n\
         decision_type=0\nleft_child={left}\nright_child={right}\n\
         leaf_value=0.1 0.2\n"
    )
}

#[test]
fn cyclic_tree_is_rejected() {
    let err = LgbModel::parse(&one_split(0, 0)).unwrap_err();
    assert!(matches!(err, Error::Parse { .. }), "got {err:?}");
}

#[test]
fn unreachable_leaf_is_rejected() {
    let err = LgbModel::parse(&one_split(-1, -1)).unwrap_err();
    assert!(matches!(err, Error::Parse { .. }), "got {err:?}");
}

#[test]
fn dense_feature_count_is_checked() {
    let model = LgbModel::parse(fixture!("tiny_binary.lgb")).unwrap();
    let err = model.predict(&[0.5, -0.2, 0.7, 1.1]).unwrap_err();
    assert!(
        matches!(
            err,
            Error::FeatureCount {
                expected: 5,
                got: 4
            }
        ),
        "got {err:?}"
    );
}

#[test]
fn huge_feature_indices_are_rejected() {
    let huge_header = format!(
        "max_feature_idx={}\nTree=0\nnum_leaves=1\nleaf_value=0.5\n",
        usize::MAX
    );
    let huge_split =
        one_split(-1, -2).replace("split_feature=0", &format!("split_feature={}", usize::MAX));
    for text in [huge_header, huge_split] {
        let err = LgbModel::parse(&text).unwrap_err();
        assert!(matches!(err, Error::Parse { .. }), "got {err:?}");
    }
}

#[test]
fn split_feature_beyond_header_bound_is_rejected() {
    let text = format!("max_feature_idx=0\n{}", one_split(-1, -2));
    LgbModel::parse(&text).unwrap();
    let err = LgbModel::parse(&text.replace("split_feature=0", "split_feature=3")).unwrap_err();
    assert!(matches!(err, Error::Parse { .. }), "got {err:?}");
}

#[test]
fn parse_error_is_reported() {
    let bad = "Tree=0\nnum_leaves=2\nsplit_feature=0\nthreshold=not_a_number\n\
               decision_type=2\nleft_child=-1\nright_child=-2\nleaf_value=0.1 0.2\n";
    assert!(matches!(
        LgbModel::parse(bad).unwrap_err(),
        Error::Parse { .. }
    ));
}

#[test]
fn empty_model_is_reported() {
    assert!(matches!(
        LgbModel::parse("objective=binary sigmoid:1\n").unwrap_err(),
        Error::EmptyModel
    ));
}

/// Parity on trained wapul models. Needs files outside the repo (the models and their inputs
/// come from private data), so it runs only on request:
///
///     WAPUL_LGBM_PARITY=<dir> cargo test -- --ignored
///
/// `<dir>` holds `<name>.txt` LightGBM models and matching `<name>.cases` files.
#[test]
#[ignore]
fn trained_model_parity() {
    let dir =
        std::env::var("WAPUL_LGBM_PARITY").expect("set WAPUL_LGBM_PARITY to the parity directory");
    let mut checked = 0;
    for entry in std::fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().is_some_and(|e| e == "cases") {
            let model =
                LgbModel::parse(&std::fs::read_to_string(path.with_extension("txt")).unwrap())
                    .unwrap();
            for (k, (row, raw, pred)) in parse_cases(&std::fs::read_to_string(&path).unwrap())
                .iter()
                .enumerate()
            {
                let name = path.file_stem().unwrap().to_string_lossy();
                assert_close(
                    &model.predict_raw_sparse(row),
                    raw,
                    &format!("{name} raw, case {k}"),
                );
                assert_close(
                    &model.predict_sparse(row),
                    pred,
                    &format!("{name} prediction, case {k}"),
                );
            }
            checked += 1;
        }
    }
    assert!(checked > 0, "no .cases files in {dir}");
}
